steps:
- name: 'node'
  entrypoint: 'bash'
  args:
  - '-c'
  - 'npm ci'
- name: 'node'
  entrypoint: 'bash'
  args:
  - '-c'
  - 'source .env.local && npm run build'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
timeout: '1600s'
