steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    while IFS= read -r line
    do
        SECRET_NAME=$$(echo $line | cut -d'=' -f1)
        gcloud secrets versions access latest --secret=$$SECRET_NAME > /workspace/$$SECRET_NAME.txt
    done < env-staging-names.txt

- name: node:18.13.0
  entrypoint: bash
  args:
  - '-c'
  - |
    source /workspace/secrets_as_env.sh
    npm run build

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud config set app/cloud_build_timeout 1600
    gcloud app deploy app.yaml --version=$COMMIT_SHA

timeout: '1600s'
