options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build'
  - '--build-arg'
  - 'NEXTAUTH_URL=${_NEXTAUTH_URL}'
  - '--build-arg'
  - 'NEXTAUTH_SECRET=${_NEXTAUTH_SECRET}'
  - '--build-arg'
  - 'NEXT_PUBLIC_LINKEDIN_CLIENT_ID=${_NEXT_PUBLIC_LINKEDIN_CLIENT_ID}'
  - '--build-arg'
  - 'LINKEDIN_CLIENT_SECRET=${_LINKEDIN_CLIENT_SECRET}'
  - '--build-arg'
  - 'NEXT_PUBLIC_LINKEDIN_REDIRECT_URI=${_NEXT_PUBLIC_LINKEDIN_REDIRECT_URI}'
  - '--build-arg'
  - 'NEXT_PUBLIC_LINKEDIN_STATE=${_NEXT_PUBLIC_LINKEDIN_STATE}'
  - '--build-arg'
  - 'GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID}'
  - '--build-arg'
  - 'GOOGLE_CLIENT_SECRET=${_GOOGLE_CLIENT_SECRET}'
  - '--build-arg'
  - 'GITHUB_CLIENT_ID=${_GITHUB_CLIENT_ID}'
  - '--build-arg'
  - 'GITHUB_CLIENT_SECRET=${_GITHUB_CLIENT_SECRET}'
  - '--build-arg'
  - 'BITBUCKET_CLIENT_ID=${_BITBUCKET_CLIENT_ID}'
  - '--build-arg'
  - 'BITBUCKET_CLIENT_SECRET=${_BITBUCKET_CLIENT_SECRET}'
  - '--build-arg'
  - 'BITBUCKET_OAUTH_CLIENT_ID=${_BITBUCKET_OAUTH_CLIENT_ID}'
  - '--build-arg'
  - 'PROJECT_ID=${_PROJECT_ID}'
  - '--build-arg'
  - 'PRIVATE_KEY_ID=${_PRIVATE_KEY_ID}'
  - '--build-arg'
  - 'PRIVATE_KEY=${_PRIVATE_KEY}'
  - '--build-arg'
  - 'CLIENT_EMAIL=${_CLIENT_EMAIL}'
  - '--build-arg'
  - 'CLIENT_ID=${_CLIENT_ID}'
  - '--build-arg'
  - 'AUTH_URI=${_AUTH_URI}'
  - '--build-arg'
  - 'TOKEN_URI=${_TOKEN_URI}'
  - '--build-arg'
  - 'AUTH_PROVIDER_X509_CERT_URL=${_AUTH_PROVIDER_X509_CERT_URL}'
  - '--build-arg'
  - 'CLIENT_X509_CERT_URL=${_CLIENT_X509_CERT_URL}'
  - '--build-arg'
  - 'PGSQL_USER=${_PGSQL_USER}'
  - '--build-arg'
  - 'PGSQL_PASSWORD=${_PGSQL_PASSWORD}'
  - '--build-arg'
  - 'PGSQL_HOST=${_PGSQL_HOST}'
  - '--build-arg'
  - 'PGSQL_PORT=${_PGSQL_PORT}'
  - '--build-arg'
  - 'PGSQL_DATABASE=${_PGSQL_DATABASE}'
  - '--build-arg'
  - 'DATABASE_URL=${_DATABASE_URL}'
  - '--build-arg'
  - 'NEXT_PUBLIC_RUDDERSTACK_CLIENT_WRITE_KEY=${_NEXT_PUBLIC_RUDDERSTACK_CLIENT_WRITE_KEY}'
  - '--build-arg'
  - 'NEXT_PUBLIC_RUDDERSTACK_CLIENT_DATAPLANE_URL=${_NEXT_PUBLIC_RUDDERSTACK_CLIENT_DATAPLANE_URL}'
  - '--build-arg'
  - 'RUDDERSTACK_SERVER_WRITE_KEY=${_RUDDERSTACK_SERVER_WRITE_KEY}'
  - '--build-arg'
  - 'RUDDERSTACK_SERVER_DATAPLANE_URL=${_RUDDERSTACK_SERVER_DATAPLANE_URL}'
  - '--build-arg'
  - 'GITLAB_CLIENT_ID=${_GITLAB_CLIENT_ID}'
  - '--build-arg'
  - 'GITLAB_CLIENT_SECRET=${_GITLAB_CLIENT_SECRET}'
  - '--build-arg'
  - 'CLARITY_ID=${_CLARITY_ID}'
  - '--build-arg'
  - 'SUBSCRIPTION_NAME=${_SUBSCRIPTION_NAME}'
  - '--build-arg'
  - 'TOPIC_NAME=${_TOPIC_NAME}'
  - '--build-arg'
  - 'NODE_ENV=${_NODE_ENV}'
  - '--no-cache'
  - '-t'
  - 'asia-docker.pkg.dev/$PROJECT_ID/asia.gcr.io/$PROJECT_ID/tmw:$COMMIT_SHA'
  - '.'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-docker.pkg.dev/$PROJECT_ID/asia.gcr.io/$PROJECT_ID/tmw:$COMMIT_SHA']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud compute instances update-container tr-test-twm \
      --container-image=asia-docker.pkg.dev/$PROJECT_ID/asia.gcr.io/$PROJECT_ID/tmw:$COMMIT_SHA \
      --zone=asia-south1-c \
      --container-port=443:3000 \
      --container-env=NEXTAUTH_URL=${_NEXTAUTH_URL},NEXTAUTH_SECRET=${_NEXTAUTH_SECRET},NEXT_PUBLIC_LINKEDIN_CLIENT_ID=${_NEXT_PUBLIC_LINKEDIN_CLIENT_ID},LINKEDIN_CLIENT_SECRET=${_LINKEDIN_CLIENT_SECRET},NEXT_PUBLIC_LINKEDIN_REDIRECT_URI=${_NEXT_PUBLIC_LINKEDIN_REDIRECT_URI},NEXT_PUBLIC_LINKEDIN_STATE=${_NEXT_PUBLIC_LINKEDIN_STATE},GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID},GOOGLE_CLIENT_SECRET=${_GOOGLE_CLIENT_SECRET},GITHUB_CLIENT_ID=${_GITHUB_CLIENT_ID},GITHUB_CLIENT_SECRET=${_GITHUB_CLIENT_SECRET},BITBUCKET_CLIENT_ID=${_BITBUCKET_CLIENT_ID},BITBUCKET_CLIENT_SECRET=${_BITBUCKET_CLIENT_SECRET},BITBUCKET_OAUTH_CLIENT_ID=${_BITBUCKET_OAUTH_CLIENT_ID},PROJECT_ID=${_PROJECT_ID},PRIVATE_KEY_ID=${_PRIVATE_KEY_ID},PRIVATE_KEY=${_PRIVATE_KEY},CLIENT_EMAIL=${_CLIENT_EMAIL},CLIENT_ID=${_CLIENT_ID},AUTH_URI=${_AUTH_URI},TOKEN_URI=${_TOKEN_URI},AUTH_PROVIDER_X509_CERT_URL=${_AUTH_PROVIDER_X509_CERT_URL},CLIENT_X509_CERT_URL=${_CLIENT_X509_CERT_URL},PGSQL_USER=${_PGSQL_USER},PGSQL_PASSWORD=${_PGSQL_PASSWORD},PGSQL_HOST=${_PGSQL_HOST},PGSQL_PORT=${_PGSQL_PORT},PGSQL_DATABASE=${_PGSQL_DATABASE},DATABASE_URL=${_DATABASE_URL},NEXT_PUBLIC_RUDDERSTACK_CLIENT_WRITE_KEY=${_NEXT_PUBLIC_RUDDERSTACK_CLIENT_WRITE_KEY},NEXT_PUBLIC_RUDDERSTACK_CLIENT_DATAPLANE_URL=${_NEXT_PUBLIC_RUDDERSTACK_CLIENT_DATAPLANE_URL},RUDDERSTACK_SERVER_WRITE_KEY=${_RUDDERSTACK_SERVER_WRITE_KEY},RUDDERSTACK_SERVER_DATAPLANE_URL=${_RUDDERSTACK_SERVER_DATAPLANE_URL},GITLAB_CLIENT_ID=${_GITLAB_CLIENT_ID},GITLAB_CLIENT_SECRET=${_GITLAB_CLIENT_SECRET},CLARITY_ID=${_CLARITY_ID},SUBSCRIPTION_NAME=${_SUBSCRIPTION_NAME},TOPIC_NAME=${_TOPIC_NAME},NODE_ENV=${_NODE_ENV}
timeout: '1600s'
