options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/tmw', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/tmw']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # SSH into the VM and run the Docker container
    gcloud compute ssh tr-test-twm --zone=asia-south1-c --command="sudo docker pull gcr.io/$PROJECT_ID/tmw && sudo docker run -d -p 3000:3000 gcr.io/$PROJECT_ID/tmw"
timeout: '1600s'
