steps:
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://mybucket/env_vars.txt', '.env.local']
- name: 'node'
  entrypoint: 'bash'
  args:
  - '-c'
  - 'npm ci && npm run build'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
